[theme]
primaryColor = "#a855f7"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = true

[server]
port = 8501
headless = true
runOnSave = true

[logger]
level = "info"

